export interface IEvent {
  _id?: string;
  title: string;
  description: string;
  date: string;
  location: string;
  image?: string;
  category: 'Conference' | 'Workshop' | 'Competition' | 'Seminar';
  isPast: boolean;
}
export interface IRegistration {
  _id?: string; // Optional because it's generated by MongoDB
  
  // Step 1: Identity
  fullName: string;
  fatherName: string;
  cnicOrFormB: string;
  dob: string | Date; // Date from picker is usually string, converted to Date in DB
  gender: 'Male' | 'Female' | 'Other';
  email: string;

  // Step 2: Location
  mobileNumber: string;
  whatsAppNumber?: string;
  district: string;
  permanentAddress?: string;
  postalAddress?: string;

  // Step 3: Academic
  currentGrade: string;
  academicPercentage?: string;
  instituteName: string;
  extracurriculars: string[]; // Array of strings e.g., ['Sports', 'Debates']

  // Step 4: Commitment
  otherAffiliations?: string;
  motivation: string;
  attendanceCommitment: 'Yes' | 'No' | 'Maybe';
  profilePicture?: string; // URL from Cloudinary
  parentalConsent: boolean;

  // Meta
  status: 'Pending' | 'Approved' | 'Rejected';
  registeredAt?: string | Date;
}