import type { Metadata } from "next";
import "./globals.css";
import { mont } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "KPSLA",
  description: "Generated by create next app",
  verification: {
    google: "ciiToynQ7Uc3vbhxryhilP9zfSZ_AahTjg73Yu2cWlg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
