import AdminHeader from "@/components/adminComp/AdminHeader";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <AdminHeader />
    {children}
    </>
  );
}
